$file = 'C:\Users\LENOVO\Downloads\SAFETEMP-main\SAFETEMP-main\safe.js'
$lines = Get-Content $file -Encoding UTF8

# Find "===== STEP 3: CHECK WHITELIST =====" line
$step3Start = -1
for ($i = 960; $i -lt 1010; $i++) {
    if ($lines[$i] -match 'STEP 3: CHECK WHITELIST') {
        $step3Start = $i
        break
    }
}
if ($step3Start -eq -1) { Write-Output "ERROR: STEP 3 not found"; exit 1 }
Write-Output "STEP 3 starts at line $($step3Start + 1)"

# Find end of STEP 3 block (the closing "return result;" after whitelist check + the comment for STEP 3B)
$step3End = -1
for ($i = $step3Start + 1; $i -lt $step3Start + 40; $i++) {
    if ($lines[$i] -match "STEP 3B: CHECK FOR DECEPTIVE") {
        $step3End = $i - 1  # line before STEP 3B comment
        break
    }
}
if ($step3End -eq -1) { Write-Output "ERROR: STEP 3 end not found"; exit 1 }
Write-Output "STEP 3 ends at line $($step3End + 1)"

# New STEP 3 replacement - whitelist is a reputation hint, NOT a free pass
$newStep3 = @(
  '      // ===== STEP 3: DOMAIN REPUTATION HINT (WHITELIST IS NOT A FREE PASS) =====',
  '      // Whitelisted domains get a reputation bonus but EVERY domain is verified',
  '      const isWhitelisted = isWhitelistedDomain(hostname);',
  '      result.isWhitelisted = isWhitelisted;',
  '',
  '      if (isWhitelisted) {',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS] Domain matches internal reputation list - running real-world verification...");',
  '        result.findings.push("[ZTAS] NOTE: Whitelist is a hint, NOT a trust bypass. Verifying against Safe Browsing + RDAP + DNS.");',
  '      } else {',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS] Domain NOT in reputation list - running deep verification...");',
  '      }',
  '',
  '      // ===== STEP 3A: TYPOSQUATTING / BRAND IMPERSONATION =====',
  '      const impersonation = detectBrandImpersonation(hostname);',
  '      if (impersonation.isImpersonation) {',
  '        result.score = 100;',
  '        result.isSafe = false;',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS] CRITICAL: BRAND IMPERSONATION DETECTED");',
  '        result.findings.push("===========================================");',
  '        result.findings.push("This domain is impersonating: " + impersonation.targetedBrand.toUpperCase());',
  '        result.findings.push("Deceptive technique: " + impersonation.type);',
  '        result.findings.push("This is a highly dangerous phishing attempt.");',
  '        result.findings.unshift("[ZTAS] BLOCK - Brand Impersonation (" + impersonation.targetedBrand + ")");',
  '        return result;',
  '      }',
  '',
  '      // ===== STEP 3B: DGA BEACON DETECTION =====',
  '      if (isDGALikeDomain(hostname)) {',
  '        result.score = 95;',
  '        result.isSafe = false;',
  '        result.findings.push("[ZTAS][DGA] DOMAIN GENERATION ALGORITHM DETECTED");',
  '        result.findings.push("Domain " + hostname + " matches DGA beacon patterns - T1568.002");',
  '        result.findings.push("Likely C2 beacon domain used by malware for command-and-control");',
  '        result.findings.unshift("[ZTAS] BLOCK - DGA Beacon Domain (C2 Communication)");',
  '        return result;',
  '      }',
  '',
  '      // ===== STEP 3C: PARALLEL TRIPLE VERIFICATION (Safe Browsing + RDAP + DNS) =====',
  '      result.findings.push("[ZTAS] Running Triple Verification: Safe Browsing API + RDAP Registry + DNS-over-HTTPS...");',
  '      const [safeBrowsingResult, rdapResult, dnsResult] = await Promise.all([',
  '        checkSafeBrowsingAPI(originalUrl),',
  '        verifyDomainRegistration(hostname),',
  '        verifyDomainExistsOnInternet(hostname)',
  '      ]);',
  '      result.safeBrowsingResult = safeBrowsingResult;',
  '',
  '      // --- Safe Browsing Verdict ---',
  '      if (safeBrowsingResult.isThreat) {',
  '        result.score = 98;',
  '        result.isSafe = false;',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS][GSB] THREAT CONFIRMED BY GOOGLE SAFE BROWSING!");',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS][GSB] Threat types: " + safeBrowsingResult.threatTypes.join(", "));',
  '        if (isWhitelisted) {',
  '          result.score = 100;',
  '          result.findings.push("[ZTAS][GSB] CRITICAL: Domain appears in whitelist BUT Google flags it as threat - COMPROMISED domain or sophisticated attack");',
  '        }',
  '        result.findings.push("[ZTAS][GSB] Do NOT visit this site. Do NOT enter any information.");',
  '        result.findings.unshift("[ZTAS] BLOCK - Confirmed Threat in Google Intelligence Database");',
  '        return result;',
  '      } else if (!safeBrowsingResult.error) {',
  '        result.findings.push("[ZTAS][GSB] Google Safe Browsing: CLEAR - not found in threat database");',
  '      } else {',
  '        result.findings.push("[ZTAS][GSB] Google Safe Browsing: API unavailable - " + safeBrowsingResult.message);',
  '      }',
  '',
  '      // --- RDAP Domain Registration Verdict ---',
  '      if (rdapResult.registered === false) {',
  '        result.score = Math.min(100, result.score + 90);',
  '        result.isSafe = false;',
  '        result.findings.push("[ZTAS][RDAP] CRITICAL: Domain NOT REGISTERED - phantom/fake domain used for phishing");',
  '        result.findings.push("[ZTAS][RDAP] This domain does not exist in any global domain registry (RDAP/IANA)");',
  '        result.findings.unshift("[ZTAS] BLOCK - Phantom Domain (Not in Global Registry)");',
  '        return result;',
  '      } else if (rdapResult.registered === true) {',
  '        result.findings.push("[ZTAS][RDAP] Domain IS registered in global registry");',
  '        if (rdapResult.registrar) result.findings.push("[ZTAS][RDAP] Registrar: " + rdapResult.registrar);',
  '        if (rdapResult.created) result.findings.push("[ZTAS][RDAP] Registration date: " + rdapResult.created.substring(0, 10));',
  '        if (rdapResult.expiry) result.findings.push("[ZTAS][RDAP] Expiry date: " + rdapResult.expiry.substring(0, 10));',
  '        if (rdapResult.isBrandNew) {',
  '          result.score = Math.min(100, result.score + 55);',
  '          result.findings.push("[ZTAS][RDAP] HIGH RISK: Domain only " + rdapResult.ageDays + " days old - brand-new domains extremely common in phishing campaigns - T1583.001");',
  '        } else if (rdapResult.isNew) {',
  '          result.score = Math.min(100, result.score + 30);',
  '          result.findings.push("[ZTAS][RDAP] WARNING: Domain only " + rdapResult.ageDays + " days old - newly registered domains are high-risk - T1583.001");',
  '        } else if (rdapResult.ageDays) {',
  '          result.findings.push("[ZTAS][RDAP] Domain age: " + rdapResult.ageDays + " days - established domain");',
  '        }',
  '      } else {',
  '        result.findings.push("[ZTAS][RDAP] RDAP registry lookup: " + (rdapResult.error || "no response"));',
  '      }',
  '',
  '      // --- DNS Existence Check ---',
  '      if (dnsResult.resolvers.length > 0) {',
  '        const rsum = dnsResult.resolvers.map(r => r.name + ":" + (r.status === 0 ? "RESOLVES" : r.status === 3 ? "NXDOMAIN" : "ERROR")).join(" | ");',
  '        result.findings.push("[ZTAS][DNS] " + rsum);',
  '        if (dnsResult.nxdomain && !dnsResult.exists) {',
  '          result.score = Math.min(100, result.score + 80);',
  '          result.findings.push("[ZTAS][DNS] CRITICAL: Domain NXDOMAIN on all resolvers - does not exist on Internet");',
  '        } else if (dnsResult.blocked) {',
  '          result.score = Math.min(100, result.score + 50);',
  '          result.findings.push("[ZTAS][DNS] Domain sinkholed by Quad9/Google - known malware/C2");',
  '        } else if (dnsResult.exists) {',
  '          result.findings.push("[ZTAS][DNS] Domain resolves successfully on Internet");',
  '        }',
  '      }',
  '',
  '      // --- Final TRIPLE LOCK verdict for this domain ---',
  '      const safeBrowsingPassed = !safeBrowsingResult.error && !safeBrowsingResult.isThreat;',
  '      const rdapPassed = rdapResult.registered !== false && !rdapResult.isBrandNew;',
  '      const dnsPassed = dnsResult.exists && !dnsResult.blocked;',
  '      const tripleLockPassed = safeBrowsingPassed && rdapPassed && dnsPassed;',
  '',
  '      if (isWhitelisted && tripleLockPassed && result.score < 30) {',
  '        // Full SAFE: whitelist reputation + all 3 verifications passed',
  '        result.score = 0;',
  '        result.isSafe = true;',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS] TRIPLE LOCK PASSED: Safe Browsing CLEAR + RDAP Registered + DNS Resolves");',
  '        result.findings.push("[ZTAS] Domain reputation: KNOWN + VERIFIED on Internet");',
  '        if (result.protocol === "HTTPS") {',
  '          result.findings.push("[ZTAS] Protocol: HTTPS - encrypted connection");',
  '          result.findings.unshift("[ZTAS] SAFE - Triple-Verified Domain: Reputation + Safe Browsing + Registry + DNS");',
  '        } else {',
  '          result.score = 20;',
  '          result.findings.push("[ZTAS] WARNING: HTTP - unencrypted. Use https://");',
  '          result.findings.unshift("[ZTAS] SAFE WITH WARNING - Triple-Verified but uses HTTP");',
  '        }',
  '        return result;',
  '      } else if (isWhitelisted && !tripleLockPassed) {',
  '        // Whitelisted BUT verification failed - suspicious',
  '        result.score = Math.min(100, result.score + 40);',
  '        result.isSafe = false;',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS] WARNING: Domain is in reputation list BUT failed real-world verification");',
  '        result.findings.push("[ZTAS] Possible: domain takeover, expired domain hijacking, or sophisticated spoofing");',
  '        result.findings.push("[ZTAS] GSB: " + (safeBrowsingPassed ? "PASS" : "FAIL") + " | RDAP: " + (rdapPassed ? "PASS" : "FAIL") + " | DNS: " + (dnsPassed ? "PASS" : "FAIL"));',
  '        result.findings.unshift("[ZTAS] ISOLATE - Known Domain FAILED Triple Verification");',
  '        return result;',
  '      } else if (!isWhitelisted && tripleLockPassed && result.score < 25) {',
  '        // Unknown domain but all verifications pass - new legitimate domain',
  '        result.score = 30;',
  '        result.isSafe = false;',
  '        result.findings.push("===========================================");',
  '        result.findings.push("[ZTAS] Domain passed all internet verifications but is NOT in ZTAS reputation list");',
  '        result.findings.push("[ZTAS] Domain is REAL and REGISTERED but unknown. Zero-Trust: treat as UNVERIFIED.");',
  '        result.findings.unshift("[ZTAS] ISOLATE - Real Domain, Not in ZTAS Whitelist (Unknown)");',
  '        return result;',
  '      }',
  '      // Fall through to heuristic deep analysis for unverified/suspicious domains',
  '      result.findings.push("===========================================");',
  '      result.findings.push("[ZTAS] Domain requires heuristic deep analysis...");',
  ''
)

$out = $lines[0..($step3Start - 1)] + $newStep3 + $lines[($step3End+1)..($lines.Length - 1)]
$out | Set-Content $file -Encoding UTF8
Write-Output "Part 2 done. Lines: $($out.Length)"
